# Generated by Django 6.0.3 on 2026-03-15 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sınav Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('duration', models.IntegerField(help_text='Dakika cinsinden', verbose_name='Süre')),
                ('total_questions', models.IntegerField(verbose_name='Soru Sayısı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Sınav',
                'verbose_name_plural': 'Sınavlar',
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Puan')),
                ('correct_count', models.IntegerField(default=0)),
                ('wrong_count', models.IntegerField(default=0)),
                ('empty_count', models.IntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam', verbose_name='Sınav')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Sınav Girişimi',
                'verbose_name_plural': 'Sınav Girişimleri',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Soru Metni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Soru Görseli')),
                ('option_a', models.CharField(max_length=255, verbose_name='A Şıkkı')),
                ('option_b', models.CharField(max_length=255, verbose_name='B Şıkkı')),
                ('option_c', models.CharField(max_length=255, verbose_name='C Şıkkı')),
                ('option_d', models.CharField(max_length=255, verbose_name='D Şıkkı')),
                ('option_e', models.CharField(blank=True, max_length=255, null=True, verbose_name='E Şıkkı (opsiyonel)')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='Doğru Cevap')),
                ('explanation', models.TextField(blank=True, help_text='Video çözüm linki veya açıklama', verbose_name='Çözüm Açıklaması')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam', verbose_name='Sınav')),
            ],
            options={
                'verbose_name': 'Soru',
                'verbose_name_plural': 'Sorular',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=1, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
            ],
            options={
                'verbose_name': 'Öğrenci Cevabı',
                'verbose_name_plural': 'Öğrenci Cevapları',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
