# Generated by Django 6.0.3 on 2026-03-16 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_add_class_and_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Konu Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='exams.topic', verbose_name='Üst Konu')),
            ],
            options={
                'verbose_name': 'Konu',
                'verbose_name_plural': 'Konular',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='questions', to='exams.topic', verbose_name='Konular'),
        ),
    ]
